export const category: {
  name: string
  region?: { ko: string; en: string }[]
}[] = [
  {
    name: '전국',
  },
  {
    name: '서울특별시',
    region: [
      { ko: '전체', en: '' },
      { ko: '관악구', en: 'GWANAK_GU' },
    ],
  },
  {
    name: '경기도',
    region: [
      { ko: '전체', en: '' },
      { ko: '연천군', en: 'YEONCHEON_GUN' },
      { ko: '남양주시', en: 'NAMYANGJU' },
      { ko: '양평군', en: 'YANGPYEONG_GUN' },
      { ko: '가평군', en: 'GAPYEONG_GUN' },
      { ko: '포천시', en: 'POCHEON_SI' },
    ],
  },
  {
    name: '세종특별자치시',
    region: [
      { ko: '전체', en: '' },
      { ko: '세종시', en: 'SEJONG_SI' },
    ],
  },
  {
    name: '충청북도',
    region: [
      { ko: '전체', en: '' },
      { ko: '청주시', en: 'CHEONGJU_SI' },
      { ko: '상당구', en: 'SANGDANG_GU' },
      { ko: '충주시', en: 'CHUNGJU_SI' },
      { ko: '제천시', en: 'JECHON_SI' },
      { ko: '영동군', en: 'YEONGDONG_GUN' },
      { ko: '진천군', en: 'JINCHEON_GUN' },
      { ko: '괴산군', en: 'GOESAN_GUN' },
      { ko: '옥천군', en: 'OKCHEON_GUN' },
      { ko: '보은군', en: 'BOEUN_GUN' },
      { ko: '음성군', en: 'EUMSEONG_GUN' },
      { ko: '단양군', en: 'DANYANG_GUN' },
    ],
  },
  {
    name: '충청남도',
    region: [
      { ko: '전체', en: '' },
      { ko: '청양군', en: 'CHEONGYANG_GUN' },
      { ko: '천안시', en: 'CHUNAN_SI' },
      { ko: '서산시', en: 'SEOSAN_SI' },
      { ko: '공주시', en: 'GONGJU_SI' },
      { ko: '논산시', en: 'NONSAN_SI' },
      { ko: '금산군', en: 'GEUMSAN_GUN' },
    ],
  },
  {
    name: '대전광역시',
    region: [
      { ko: '전체', en: '' },
      {
        ko: '대덕구',
        en: 'DAEDEOK_GU',
      },
      {
        ko: '중구',
        en: 'JUNG_GU',
      },
      { ko: '동구', en: 'JUNG_GU' },
      { ko: '서구', en: 'SEO_GU' },
    ],
  },
  {
    name: '전라북도',
    region: [
      { ko: '전체', en: '' },
      { ko: '진안군', en: 'JINAN_GUN' },
      { ko: '고창군', en: 'GOCHANG_GUN' },
      { ko: '정읍시', en: 'JEONGEUP_SI' },
      { ko: '임실군', en: 'IMSIL_GUN' },
      { ko: '김제시', en: 'GIMJE_SI' },
      { ko: '장수군', en: 'JANGSU_GUN' },
      { ko: '완주군', en: 'WANJU_GUN' },
      { ko: '남원시', en: 'NAMWON_SI' },
      { ko: '순창군', en: 'SUNCHANG_GUN' },
      { ko: '무주군', en: 'MUJU_GUN' },
    ],
  },
  {
    name: '전라남도',
    region: [
      { ko: '전체', en: '' },
      { ko: '곡성군', en: 'GOKSEONG_GUN' },
      { ko: '장성군', en: 'JANGSEONG_GUN' },
      { ko: '영암군', en: 'YEONGAM_GUN' },
      { ko: '화순군', en: 'HWASUN_GUN' },
      { ko: '장흥군', en: 'JANGHEUNG_GUN' },
      { ko: '담양군', en: 'DAMYANG_GUN' },
      { ko: '해남군', en: 'HAENAM_GUN' },
      { ko: '구례군', en: 'GURYE_GUN' },
      { ko: '순천시', en: 'SUNCHEON_SI' },
      { ko: '광양시', en: 'GWANGYANG_SI' },
      { ko: '보성군', en: 'BOSEONG_GUN' },
      { ko: '강진군', en: 'GANGJIN_GUN' },
    ],
  },
  {
    name: '광주광역시',
    region: [
      { ko: '전체', en: '' },
      { ko: '광산구', en: 'GWANGSAN_GU' },
    ],
  },
  {
    name: '강원도',
    region: [
      { ko: '전체', en: '' },
      { ko: '정선군', en: 'JEONGSEON_GUN' },
      { ko: '춘천시', en: 'CHUNCHEON_SI' },
      { ko: '평창군', en: 'PYEONGCHANG_GUN' },
      { ko: '인제군', en: 'INJE_GUN' },
      { ko: '양구군', en: 'YANGGU_GUN' },
      { ko: '양양군', en: 'YANGYANG_GUN' },
      { ko: '삼척시', en: 'SAMCHEOK_SI' },
      { ko: '원주시', en: 'WONJU_SI' },
      { ko: '강릉시', en: 'GANGNEUNG_SI' },
      { ko: '화천군', en: 'HWACHEON_GUN' },
      { ko: '철원군', en: 'CHEOLWON_GUN' },
      { ko: '동해시', en: 'DONGHAE_SI' },
      { ko: '홍천군', en: 'HONGCHEON_GUN' },
      { ko: '횡성군', en: 'HOENGSEONG_GUN' },
      { ko: '영월군', en: 'YEONGWOL_GUN' },
    ],
  },
  {
    name: '경상북도',
    region: [
      { ko: '전체', en: '' },
      { ko: '영주시', en: 'YEONGJU_SI' },
      { ko: '영천시', en: 'YEONGCHEON_SI' },
      { ko: '영덕군', en: 'YEONGDEOK_GUN' },
      { ko: '문경시', en: 'MUNGYEONG_SI' },
      { ko: '청송군', en: 'CHEONGSONG_GUN' },
      { ko: '봉화군', en: 'BONGHWA_GUN' },
      { ko: '김천시', en: 'GIMCHEON_SI' },
      { ko: '울진군', en: 'ULJIN_GUN' },
      { ko: '고령군', en: 'GORYEONG_GUN' },
      { ko: '성주군', en: 'SEONGJU_GUN' },
      { ko: '포항시', en: 'POHANG_SI' },
      { ko: '상주시', en: 'SANGJU_SI' },
      { ko: '청도군', en: 'CHEONGDO_GUN' },
      { ko: '안동시', en: 'ANDONG_SI' },
      { ko: '의성군', en: 'UISEONG_GUN' },
      { ko: '칠곡군', en: 'CHILGOK_GUN' },
      { ko: '경주시', en: 'GYEONGJU_SI' },
      { ko: '예천군', en: 'YECHON_GUN' },
      { ko: '군위군', en: 'GUNWI_GUN' },
      { ko: '영양군', en: 'YEONGYANG_GUN' },
    ],
  },
  {
    name: '경상남도',
    region: [
      { ko: '전체', en: '' },
      { ko: '사천시', en: 'SACHEON_SI' },
      { ko: '김해시', en: 'GIMHAE_SI' },
      { ko: '양산시', en: 'YANGSAN_SI' },
      { ko: '거창군', en: 'GEOCHANG_GUN' },
      { ko: '합천군', en: 'HAPCHEON_GUN' },
      { ko: '창원시', en: 'CHANGWON_SI' },
      { ko: '진해구', en: 'JINHAE_GU' },
      { ko: '함안군', en: 'HAMAN_GUN' },
      { ko: '의령군', en: 'UIRYEONG_GUN' },
      { ko: '창녕군', en: 'CHANGNYEONG_GUN' },
      { ko: '마산합포구', en: 'MASAN_HAPPO_GU' },
      { ko: '밀양시', en: 'MIRYANG_SI' },
      { ko: '마산회원구', en: 'MASAN_HOEWON_GU' },
      { ko: '남해군', en: 'NAMHAE_GUN' },
      { ko: '하동군', en: 'HADONG_GUN' },
      { ko: '고성군', en: 'GOSEONG_GUN' },
      { ko: '함양군', en: 'HAMYANG_GUN' },
      { ko: '산청군', en: 'SANCHEONG_GUN' },
    ],
  },
  {
    name: '부산광역시',
    region: [
      { ko: '전체', en: '' },
      { ko: '해운대구', en: 'HAEUNDAE_GU' },
      { ko: '금정구', en: 'GEUMJEONG_GU' },
      { ko: '북구', en: 'BUK_GU' },
      { ko: '기장군', en: 'GIJANG_GUN' },
    ],
  },
  {
    name: '울산광역시',
    region: [
      { ko: '전체', en: '' },
      { ko: '울주군', en: 'ULJU_GUN' },
    ],
  },
  {
    name: '제주특별자치도',
    region: [
      { ko: '전체', en: '' },
      { ko: '제주시', en: 'JEJU_SI' },
      { ko: '서귀포시', en: 'SEOGWIPO_SI' },
    ],
  },
]
