import { ChatRoomItem } from 'types/chat'

export const chatList: {
  memberName: String
  chatRooms: ChatRoomItem[]
} = {
  memberName: 'yj2727',
  chatRooms: [
    {
      chatRoomId: 8,
      chatRoomTitle: '계곡탐험가 와(과)의 채팅방입니다.',
      otherUserProfileImage: null,
      otherUserNick: '계곡탐험가',
      createdChatRoomDate: '2024-05-05 22:10:17',
      lastMessageContent: '감사합니다~',
      unReadMessageCount: 0,
      lastMessageTime: '2024-05-05 23:40:17',
    },
    {
      chatRoomId: 1,
      chatRoomTitle: 'yunej 와(과)의 채팅방입니다.',
      otherUserProfileImage: '/img/dummy/profile-img4.jpg',
      otherUserNick: 'yunej',
      createdChatRoomDate: '2024-05-06 19:43:00',
      lastMessageContent: '감사합니다',
      unReadMessageCount: 0,
      lastMessageTime: '2024-05-06 21:28:28',
    },
    {
      chatRoomId: 7,
      chatRoomTitle: 'hzei27 와(과)의 채팅방입니다.',
      otherUserProfileImage: '/img/dummy/profile-img3.jpg',
      otherUserNick: 'hzei27',
      createdChatRoomDate: '2024-05-06 19:30:03',
      lastMessageContent: '넵',
      unReadMessageCount: 0,
      lastMessageTime: '2024-05-06 22:10:56',
    },
  ],
}

export const chat1 = {
  memberId: 6,
  chatRoomId: 8,
  chatMessages: {
    content: [
      {
        chatMessageId: '676d385691149759b1c4493f',
        senderId: 5,
        myMsg: false,
        content: '노란색 튜브 맞습니다',
        createdAt: '2024-05-05 22:10:17',
        readCount: 0,
        chatType: null,
        imageUrl: null,
      },
      {
        chatMessageId: '676d385091149759b1c4493e',
        senderId: 6,
        myMsg: true,
        content: '근처 편의점에 맡겨놨어요~',
        createdAt: '2024-05-05 22:20:19',
        readCount: 0,
        chatType: null,
        imageUrl: null,
      },
      {
        chatMessageId: '676d385691149759b1c4493f',
        senderId: 5,
        myMsg: false,
        content: '감사합니다~',
        createdAt: '2024-05-05 23:40:17',
        readCount: 0,
        chatType: null,
        imageUrl: null,
      },
    ],
    pageable: {
      sort: {
        empty: false,
        sorted: true,
        unsorted: false,
      },
      offset: 0,
      pageNumber: 0,
      pageSize: 20,
      unpaged: false,
      paged: true,
    },
    size: 20,
    first: true,
    last: false,
    number: 0,
    sort: {
      empty: false,
      sorted: true,
      unsorted: false,
    },
    numberOfElements: 20,
    empty: false,
  },
}

export const chat2 = {
  memberId: 6,
  chatRoomId: 1,
  chatMessages: {
    content: [
      {
        chatMessageId: '676d385691149759b1c4493f',
        senderId: 5,
        myMsg: false,
        content: '금오동천에서 아이폰 15 주우셨나요?',
        createdAt: '2024-05-06 19:43:00',
        readCount: 0,
        chatType: null,
        imageUrl: null,
      },
      {
        chatMessageId: '676d385091149759b1c4493e',
        senderId: 6,
        myMsg: true,
        content: '제가 갖고 있어요',
        createdAt: '2024-05-06 20:20:19',
        readCount: 0,
        chatType: null,
        imageUrl: null,
      },
      {
        chatMessageId: '676d385091149759b1c4493e',
        senderId: 6,
        myMsg: true,
        content: '',
        createdAt: '2024-05-06 20:21:19',
        readCount: 0,
        chatType: 'IMAGE',
        imageUrl: '/img/dummy/아이폰.jpg',
      },
      {
        chatMessageId: '676d385091149759b1c4493e',
        senderId: 6,
        myMsg: true,
        content: '금오 파출소에 맡길게요~',
        createdAt: '2024-05-06 20:21:40',
        readCount: 0,
        chatType: null,
        imageUrl: '/img/dummy/아이폰.jpg',
      },
      {
        chatMessageId: '676d385691149759b1c4493f',
        senderId: 5,
        myMsg: false,
        content: '감사합니다',
        createdAt: '2024-05-06 21:28:28',
        readCount: 0,
        chatType: null,
        imageUrl: null,
      },
    ],
    pageable: {
      sort: {
        empty: false,
        sorted: true,
        unsorted: false,
      },
      offset: 0,
      pageNumber: 0,
      pageSize: 20,
      unpaged: false,
      paged: true,
    },
    size: 20,
    first: true,
    last: false,
    number: 0,
    sort: {
      empty: false,
      sorted: true,
      unsorted: false,
    },
    numberOfElements: 20,
    empty: false,
  },
}

export const chat3 = {
  memberId: 6,
  chatRoomId: 7,
  chatMessages: {
    content: [
      {
        chatMessageId: '676d385091149759b1c4493e',
        senderId: 6,
        myMsg: true,
        content:
          '관악산 계곡에서 핸드폰 잃어버렸는데 게시판 글 보고 연락드립니다',
        createdAt: '2024-05-06 19:30:03',
        readCount: 0,
        chatType: null,
        imageUrl: null,
      },
      {
        chatMessageId: '676d385691149759b1c4493f',
        senderId: 5,
        myMsg: false,
        content: '경찰서에 맡겨놨어요',
        createdAt: '2024-05-06 19:43:00',
        readCount: 0,
        chatType: null,
        imageUrl: null,
      },
      {
        chatMessageId: '676d385091149759b1c4493e',
        senderId: 6,
        myMsg: true,
        content: '감사합니다',
        createdAt: '2024-05-06 20:20:19',
        readCount: 0,
        chatType: null,
        imageUrl: null,
      },
      {
        chatMessageId: '676d385691149759b1c4493f',
        senderId: 5,
        myMsg: false,
        content: '넵',
        createdAt: '2024-05-06 22:10:56',
        readCount: 0,
        chatType: null,
        imageUrl: null,
      },
    ],
    pageable: {
      sort: {
        empty: false,
        sorted: true,
        unsorted: false,
      },
      offset: 0,
      pageNumber: 0,
      pageSize: 20,
      unpaged: false,
      paged: true,
    },
    size: 20,
    first: true,
    last: false,
    number: 0,
    sort: {
      empty: false,
      sorted: true,
      unsorted: false,
    },
    numberOfElements: 20,
    empty: false,
  },
}
