import { LostList } from 'types/lost-found'

export const data: LostList[] = [
  {
    id: 18,
    title: '금오동천에서 키링 봤습니다',
    content: '채팅 주세요',
    author: 'yunej',
    commentCnt: 0,
    postCreateAt: '2024-05-06 19:28:16',
    postImage: '/img/dummy/키링.jpg',
    category: 'FOUND',
  },
  {
    id: 17,
    title: '금오계곡에서 찾았어요',
    content: '아이폰 15 입니다',
    author: 'yj2727',
    commentCnt: 1,
    postCreateAt: '2024-05-05 21:19:49',
    postImage: '/img/dummy/아이폰.jpg',
    category: 'FOUND',
  },
  {
    id: 16,
    title: '핸드폰 잃어버리신 분 채팅주세요',
    content: '관악산 계곡에서 주웠어요~',
    author: 'hzei27',
    commentCnt: 2,
    postCreateAt: '2024-05-05 21:16:13',
    postImage: '',
    category: 'FOUND',
  },
  {
    id: 15,
    title: '튜브 보신 분 있나요?',
    content: '채팅 부탁드려요',
    author: '계곡탐험가',
    commentCnt: 3,
    postCreateAt: '2024-05-05 21:15:14',
    postImage: '',
    category: 'LOST',
  },
  {
    id: 14,
    title: '관악산 계곡에서 키링 보신분 있나요?',
    content: '쿠로미 키링입니다 ㅜㅜ',
    author: 'yj2727',
    commentCnt: 0,
    postCreateAt: '2024-05-05 21:06:14',
    postImage: '',
    category: 'LOST',
  },
  {
    id: 11,
    title: '관악산 계곡에서 오리발 찾아요',
    content: '이렇게 생긴 거 보신 분 있으신가요?',
    author: 'yunej',
    commentCnt: 2,
    postCreateAt: '2024-05-05 20:57:35',
    postImage: '/img/dummy/오리발.png',
    category: 'LOST',
  },
]

export const dataLost: LostList[] = [
  {
    id: 15,
    title: '튜브 보신 분 있나요?',
    content: '채팅 부탁드려요',
    author: '계곡탐험가',
    commentCnt: 3,
    postCreateAt: '2024-05-05 21:15:14',
    postImage: '',
    category: 'LOST',
  },
  {
    id: 14,
    title: '관악산 계곡에서 키링 보신분 있나요?',
    content: '쿠로미 키링입니다 ㅜㅜ',
    author: 'yj2727',
    commentCnt: 0,
    postCreateAt: '2024-05-05 21:06:14',
    postImage: '',
    category: 'LOST',
  },
  {
    id: 11,
    title: '관악산 계곡에서 오리발 찾아요',
    content: '이렇게 생긴 거 보신 분 있으신가요?',
    author: 'yunej',
    commentCnt: 2,
    postCreateAt: '2024-05-05 20:57:35',
    postImage: '/img/dummy/오리발.png',
    category: 'LOST',
  },
]

export const dataFOUND: LostList[] = [
  {
    id: 18,
    title: '금오동천에서 키링 봤습니다',
    content: '채팅 주세요',
    author: 'yunej',
    commentCnt: 0,
    postCreateAt: '2024-05-06 19:28:16',
    postImage: '/img/dummy/키링.jpg',
    category: 'FOUND',
  },
  {
    id: 17,
    title: '금오계곡에서 찾았어요',
    content: '아이폰 15 입니다',
    author: 'yj2727',
    commentCnt: 1,
    postCreateAt: '2024-05-05 21:19:49',
    postImage: '/img/dummy/아이폰.jpg',
    category: 'FOUND',
  },
  {
    id: 16,
    title: '핸드폰 잃어버리신 분 채팅주세요',
    content: '관악산 계곡에서 주웠어요~',
    author: 'hzei27',
    commentCnt: 2,
    postCreateAt: '2024-05-05 21:16:13',
    postImage: null,
    category: 'FOUND',
  },
]

export const data1: LostList[] = [
  {
    id: 16,
    title: '핸드폰 잃어버리신 분 채팅주세요',
    content: '관악산 계곡에서 주웠어요~',
    author: 'hzei27',
    commentCnt: 2,
    postCreateAt: '2024-05-05 21:16:13',
    postImage: null,
    category: 'FOUND',
  },
  {
    id: 14,
    title: '관악산 계곡에서 키링 보신분 있나요?',
    content: '쿠로미 키링입니다 ㅜㅜ',
    author: 'yj2727',
    commentCnt: 0,
    postCreateAt: '2024-05-05 21:06:14',
    postImage: null,
    category: 'LOST',
  },
  {
    id: 11,
    title: '관악산 계곡에서 오리발 찾아요',
    content: '이렇게 생긴 거 보신 분 있으신가요?',
    author: 'yunej',
    commentCnt: 2,
    postCreateAt: '2024-05-05 20:57:35',
    postImage: '/img/dummy/오리발.png',
    category: 'LOST',
  },
]

export const data1867: LostList[] = [
  {
    id: 18,
    title: '금오동천에서 키링 봤습니다',
    content: '채팅 주세요',
    author: 'yunej',
    commentCnt: 0,
    postCreateAt: '2024-05-06 19:28:16',
    postImage: '/img/dummy/키링.jpg',
    category: 'FOUND',
  },
  {
    id: 17,
    title: '금오계곡에서 찾았어요',
    content: '아이폰 15 입니다',
    author: 'yj2727',
    commentCnt: 1,
    postCreateAt: '2024-05-05 21:19:49',
    postImage: '/img/dummy/아이폰.jpg',
    category: 'FOUND',
  },
]
