import { MainData } from 'types/main'

export const data: MainData = {
  nationalWeather: [
    {
      weatherDate: '2024-05-14',
      dailyNationalWeather: [
        {
          region: '백령',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 14.53,
          maxTemp: 15.04,
          rainPrecipitation: 0,
          humidity: 68,
          windSpeed: 8.55,
          clouds: 5,
          dayFeelsLike: 14.09,
        },
        {
          region: '서울',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 10.86,
          maxTemp: 18.58,
          rainPrecipitation: 0,
          humidity: 70,
          windSpeed: 4.41,
          clouds: 4,
          dayFeelsLike: 14.39,
        },
        {
          region: '춘천',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 12.36,
          maxTemp: 20.75,
          rainPrecipitation: 0,
          humidity: 68,
          windSpeed: 4.27,
          clouds: 4,
          dayFeelsLike: 15.64,
        },
        {
          region: '강릉',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 13.74,
          maxTemp: 20.27,
          rainPrecipitation: 0,
          humidity: 72,
          windSpeed: 5.86,
          clouds: 5,
          dayFeelsLike: 16.11,
        },
        {
          region: '수원',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 11.35,
          maxTemp: 19.45,
          rainPrecipitation: 0,
          humidity: 71,
          windSpeed: 4.23,
          clouds: 4,
          dayFeelsLike: 15.56,
        },
        {
          region: '청주',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 10.86,
          maxTemp: 20.84,
          rainPrecipitation: 0,
          humidity: 72,
          windSpeed: 3.42,
          clouds: 4,
          dayFeelsLike: 16.84,
        },
        {
          region: '울릉/독도',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 16.06,
          maxTemp: 17.34,
          rainPrecipitation: 0,
          humidity: 70,
          windSpeed: 6.81,
          clouds: 5,
          dayFeelsLike: 15.55,
        },
        {
          region: '대전',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 10.64,
          maxTemp: 20.63,
          rainPrecipitation: 0,
          humidity: 72,
          windSpeed: 3.29,
          clouds: 4,
          dayFeelsLike: 16.93,
        },
        {
          region: '안동',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 12.41,
          maxTemp: 20.46,
          rainPrecipitation: 0,
          humidity: 71,
          windSpeed: 4.46,
          clouds: 4,
          dayFeelsLike: 16.43,
        },
        {
          region: '전주',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 11.17,
          maxTemp: 19.87,
          rainPrecipitation: 0,
          humidity: 71,
          windSpeed: 3.14,
          clouds: 4,
          dayFeelsLike: 16.84,
        },
        {
          region: '대구',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 12.43,
          maxTemp: 19.54,
          rainPrecipitation: 0,
          humidity: 71,
          windSpeed: 4.58,
          clouds: 4,
          dayFeelsLike: 16.27,
        },
        {
          region: '울산',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 15.12,
          maxTemp: 18.84,
          rainPrecipitation: 0,
          humidity: 68,
          windSpeed: 5.37,
          clouds: 4,
          dayFeelsLike: 16.25,
        },
        {
          region: '광주',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 14.65,
          maxTemp: 18.17,
          rainPrecipitation: 0,
          humidity: 73,
          windSpeed: 4.11,
          clouds: 4,
          dayFeelsLike: 16.34,
        },
        {
          region: '목포',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 15.61,
          maxTemp: 17.23,
          rainPrecipitation: 0,
          humidity: 73,
          windSpeed: 4.54,
          clouds: 4,
          dayFeelsLike: 15.92,
        },
        {
          region: '부산',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 15.87,
          maxTemp: 18.75,
          rainPrecipitation: 0,
          humidity: 69,
          windSpeed: 5.46,
          clouds: 4,
          dayFeelsLike: 16.52,
        },
        {
          region: '제주',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 8.99,
          maxTemp: 9.36,
          rainPrecipitation: 0,
          humidity: 74,
          windSpeed: 4.42,
          clouds: 2,
          dayFeelsLike: 7.49,
        },
        {
          region: '여수',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 16,
          maxTemp: 18.38,
          rainPrecipitation: 0,
          humidity: 74,
          windSpeed: 4.72,
          clouds: 3,
          dayFeelsLike: 16.8,
        },
      ],
    },
    {
      weatherDate: '2024-05-15',
      dailyNationalWeather: [
        {
          region: '백령',
          weatherIcon: '10d',
          weatherDesc: '실 비',
          minTemp: 13.13,
          maxTemp: 14.53,
          rainPrecipitation: 7.92,
          humidity: 85,
          windSpeed: 11.58,
          clouds: 90,
          dayFeelsLike: 12.95,
        },
        {
          region: '서울',
          weatherIcon: '10d',
          weatherDesc: '보통 비',
          minTemp: 8.06,
          maxTemp: 14.06,
          rainPrecipitation: 9.95,
          humidity: 80,
          windSpeed: 6.74,
          clouds: 38,
          dayFeelsLike: 13.38,
        },
        {
          region: '춘천',
          weatherIcon: '10d',
          weatherDesc: '보통 비',
          minTemp: 8.76,
          maxTemp: 15.09,
          rainPrecipitation: 15.22,
          humidity: 74,
          windSpeed: 5.04,
          clouds: 38,
          dayFeelsLike: 14.59,
        },
        {
          region: '강릉',
          weatherIcon: '10d',
          weatherDesc: '실 비',
          minTemp: 10.1,
          maxTemp: 15.94,
          rainPrecipitation: 11.15,
          humidity: 69,
          windSpeed: 7.6,
          clouds: 24,
          dayFeelsLike: 15.39,
        },
        {
          region: '수원',
          weatherIcon: '10d',
          weatherDesc: '실 비',
          minTemp: 8.83,
          maxTemp: 15.4,
          rainPrecipitation: 7.2,
          humidity: 79,
          windSpeed: 7.15,
          clouds: 30,
          dayFeelsLike: 14.54,
        },
        {
          region: '청주',
          weatherIcon: '10d',
          weatherDesc: '실 비',
          minTemp: 9.49,
          maxTemp: 17.63,
          rainPrecipitation: 4.15,
          humidity: 74,
          windSpeed: 6.1,
          clouds: 17,
          dayFeelsLike: 15.73,
        },
        {
          region: '울릉/독도',
          weatherIcon: '10d',
          weatherDesc: '실 비',
          minTemp: 12.85,
          maxTemp: 17.2,
          rainPrecipitation: 3.55,
          humidity: 76,
          windSpeed: 11.35,
          clouds: 10,
          dayFeelsLike: 16.57,
        },
        {
          region: '대전',
          weatherIcon: '10d',
          weatherDesc: '실 비',
          minTemp: 10.21,
          maxTemp: 17.62,
          rainPrecipitation: 2.49,
          humidity: 74,
          windSpeed: 6.42,
          clouds: 15,
          dayFeelsLike: 15.9,
        },
        {
          region: '안동',
          weatherIcon: '10d',
          weatherDesc: '실 비',
          minTemp: 9.91,
          maxTemp: 18.76,
          rainPrecipitation: 6.23,
          humidity: 67,
          windSpeed: 5.89,
          clouds: 11,
          dayFeelsLike: 15.74,
        },
        {
          region: '전주',
          weatherIcon: '10d',
          weatherDesc: '실 비',
          minTemp: 11.55,
          maxTemp: 17.2,
          rainPrecipitation: 0.56,
          humidity: 74,
          windSpeed: 7.78,
          clouds: 13,
          dayFeelsLike: 16.04,
        },
        {
          region: '대구',
          weatherIcon: '10d',
          weatherDesc: '실 비',
          minTemp: 11.24,
          maxTemp: 18.54,
          rainPrecipitation: 2.05,
          humidity: 69,
          windSpeed: 7.64,
          clouds: 8,
          dayFeelsLike: 15.77,
        },
        {
          region: '울산',
          weatherIcon: '10d',
          weatherDesc: '실 비',
          minTemp: 13.37,
          maxTemp: 18.93,
          rainPrecipitation: 2.57,
          humidity: 70,
          windSpeed: 9.47,
          clouds: 6,
          dayFeelsLike: 16.67,
        },
        {
          region: '광주',
          weatherIcon: '10d',
          weatherDesc: '실 비',
          minTemp: 13.57,
          maxTemp: 16.56,
          rainPrecipitation: 0.16,
          humidity: 73,
          windSpeed: 9.77,
          clouds: 12,
          dayFeelsLike: 16.03,
        },
        {
          region: '목포',
          weatherIcon: '02d',
          weatherDesc: '약간의 구름이 낀 하늘',
          minTemp: 14.25,
          maxTemp: 16.35,
          rainPrecipitation: 0,
          humidity: 73,
          windSpeed: 10.62,
          clouds: 12,
          dayFeelsLike: 15.95,
        },
        {
          region: '부산',
          weatherIcon: '10d',
          weatherDesc: '실 비',
          minTemp: 14.33,
          maxTemp: 18.79,
          rainPrecipitation: 1.41,
          humidity: 71,
          windSpeed: 9.61,
          clouds: 6,
          dayFeelsLike: 16.97,
        },
        {
          region: '제주',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 7.54,
          maxTemp: 9.25,
          rainPrecipitation: 0,
          humidity: 68,
          windSpeed: 10.59,
          clouds: 7,
          dayFeelsLike: 6.68,
        },
        {
          region: '여수',
          weatherIcon: '10d',
          weatherDesc: '실 비',
          minTemp: 14.43,
          maxTemp: 17.53,
          rainPrecipitation: 0.11,
          humidity: 70,
          windSpeed: 9.41,
          clouds: 8,
          dayFeelsLike: 16.46,
        },
      ],
    },
    {
      weatherDate: '2024-05-16',
      dailyNationalWeather: [
        {
          region: '백령',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 13.13,
          maxTemp: 14.77,
          rainPrecipitation: 0,
          humidity: 61,
          windSpeed: 8.59,
          clouds: 5,
          dayFeelsLike: 12.53,
        },
        {
          region: '서울',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 8.06,
          maxTemp: 15.93,
          rainPrecipitation: 0,
          humidity: 75,
          windSpeed: 6.05,
          clouds: 8,
          dayFeelsLike: 11.09,
        },
        {
          region: '춘천',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 8.76,
          maxTemp: 17.7,
          rainPrecipitation: 0,
          humidity: 76,
          windSpeed: 5.34,
          clouds: 9,
          dayFeelsLike: 11.86,
        },
        {
          region: '강릉',
          weatherIcon: '10d',
          weatherDesc: '실 비',
          minTemp: 10.1,
          maxTemp: 17.43,
          rainPrecipitation: 0.18,
          humidity: 75,
          windSpeed: 5.97,
          clouds: 11,
          dayFeelsLike: 12.05,
        },
        {
          region: '수원',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 8.83,
          maxTemp: 16.76,
          rainPrecipitation: 0,
          humidity: 77,
          windSpeed: 5.98,
          clouds: 8,
          dayFeelsLike: 12.12,
        },
        {
          region: '청주',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 9.49,
          maxTemp: 17.84,
          rainPrecipitation: 0,
          humidity: 77,
          windSpeed: 4.84,
          clouds: 9,
          dayFeelsLike: 12.73,
        },
        {
          region: '울릉/독도',
          weatherIcon: '10d',
          weatherDesc: '실 비',
          minTemp: 12.85,
          maxTemp: 16.3,
          rainPrecipitation: 1.84,
          humidity: 62,
          windSpeed: 11.15,
          clouds: 39,
          dayFeelsLike: 13.38,
        },
        {
          region: '대전',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 10.21,
          maxTemp: 17.79,
          rainPrecipitation: 0,
          humidity: 76,
          windSpeed: 4.57,
          clouds: 9,
          dayFeelsLike: 12.92,
        },
        {
          region: '안동',
          weatherIcon: '10d',
          weatherDesc: '실 비',
          minTemp: 9.91,
          maxTemp: 17.52,
          rainPrecipitation: 0.67,
          humidity: 71,
          windSpeed: 5.89,
          clouds: 12,
          dayFeelsLike: 12.18,
        },
        {
          region: '전주',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 11.13,
          maxTemp: 17.45,
          rainPrecipitation: 0,
          humidity: 75,
          windSpeed: 5.29,
          clouds: 8,
          dayFeelsLike: 13.22,
        },
        {
          region: '대구',
          weatherIcon: '10d',
          weatherDesc: '실 비',
          minTemp: 11.24,
          maxTemp: 17.01,
          rainPrecipitation: 0.66,
          humidity: 69,
          windSpeed: 7.64,
          clouds: 14,
          dayFeelsLike: 12.34,
        },
        {
          region: '울산',
          weatherIcon: '10d',
          weatherDesc: '실 비',
          minTemp: 13.37,
          maxTemp: 16.71,
          rainPrecipitation: 1.52,
          humidity: 66,
          windSpeed: 9.47,
          clouds: 29,
          dayFeelsLike: 13.28,
        },
        {
          region: '광주',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 13.57,
          maxTemp: 16.49,
          rainPrecipitation: 0,
          humidity: 74,
          windSpeed: 7.99,
          clouds: 7,
          dayFeelsLike: 13.5,
        },
        {
          region: '목포',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 14.25,
          maxTemp: 15.82,
          rainPrecipitation: 0,
          humidity: 72,
          windSpeed: 8.81,
          clouds: 8,
          dayFeelsLike: 13.63,
        },
        {
          region: '부산',
          weatherIcon: '10d',
          weatherDesc: '실 비',
          minTemp: 14.33,
          maxTemp: 16.78,
          rainPrecipitation: 0.97,
          humidity: 67,
          windSpeed: 9.61,
          clouds: 30,
          dayFeelsLike: 13.71,
        },
        {
          region: '제주',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 7.33,
          maxTemp: 8.22,
          rainPrecipitation: 0,
          humidity: 71,
          windSpeed: 10.59,
          clouds: 8,
          dayFeelsLike: 2.74,
        },
        {
          region: '여수',
          weatherIcon: '02d',
          weatherDesc: '약간의 구름이 낀 하늘',
          minTemp: 14.42,
          maxTemp: 16.62,
          rainPrecipitation: 0,
          humidity: 73,
          windSpeed: 9.41,
          clouds: 11,
          dayFeelsLike: 13.82,
        },
      ],
    },
    {
      weatherDate: '2024-05-17',
      dailyNationalWeather: [
        {
          region: '백령',
          weatherIcon: '04d',
          weatherDesc: '튼구름',
          minTemp: 13.75,
          maxTemp: 14.44,
          rainPrecipitation: 0,
          humidity: 74,
          windSpeed: 9.21,
          clouds: 73,
          dayFeelsLike: 13.64,
        },
        {
          region: '서울',
          weatherIcon: '04d',
          weatherDesc: '튼구름',
          minTemp: 9.93,
          maxTemp: 17.24,
          rainPrecipitation: 0,
          humidity: 74,
          windSpeed: 4.46,
          clouds: 71,
          dayFeelsLike: 12.76,
        },
        {
          region: '춘천',
          weatherIcon: '04d',
          weatherDesc: '튼구름',
          minTemp: 10.85,
          maxTemp: 19.12,
          rainPrecipitation: 0,
          humidity: 72,
          windSpeed: 4.63,
          clouds: 71,
          dayFeelsLike: 13.79,
        },
        {
          region: '강릉',
          weatherIcon: '04d',
          weatherDesc: '튼구름',
          minTemp: 11.93,
          maxTemp: 19.27,
          rainPrecipitation: 0,
          humidity: 69,
          windSpeed: 5.97,
          clouds: 64,
          dayFeelsLike: 14.03,
        },
        {
          region: '수원',
          weatherIcon: '04d',
          weatherDesc: '튼구름',
          minTemp: 10.49,
          maxTemp: 18.27,
          rainPrecipitation: 0,
          humidity: 74,
          windSpeed: 4.16,
          clouds: 68,
          dayFeelsLike: 13.71,
        },
        {
          region: '청주',
          weatherIcon: '04d',
          weatherDesc: '튼구름',
          minTemp: 9.65,
          maxTemp: 19.67,
          rainPrecipitation: 0,
          humidity: 71,
          windSpeed: 3.4,
          clouds: 60,
          dayFeelsLike: 14.38,
        },
        {
          region: '울릉/독도',
          weatherIcon: '03d',
          weatherDesc: '구름조금',
          minTemp: 15.91,
          maxTemp: 17.81,
          rainPrecipitation: 0,
          humidity: 72,
          windSpeed: 8.12,
          clouds: 46,
          dayFeelsLike: 15.44,
        },
        {
          region: '대전',
          weatherIcon: '04d',
          weatherDesc: '튼구름',
          minTemp: 9.65,
          maxTemp: 19.45,
          rainPrecipitation: 0,
          humidity: 70,
          windSpeed: 3.27,
          clouds: 58,
          dayFeelsLike: 14.49,
        },
        {
          region: '안동',
          weatherIcon: '04d',
          weatherDesc: '튼구름',
          minTemp: 11.24,
          maxTemp: 19.63,
          rainPrecipitation: 0,
          humidity: 67,
          windSpeed: 4.77,
          clouds: 52,
          dayFeelsLike: 14.09,
        },
        {
          region: '전주',
          weatherIcon: '04d',
          weatherDesc: '튼구름',
          minTemp: 10.58,
          maxTemp: 18.69,
          rainPrecipitation: 0,
          humidity: 69,
          windSpeed: 3.11,
          clouds: 56,
          dayFeelsLike: 14.67,
        },
        {
          region: '대구',
          weatherIcon: '03d',
          weatherDesc: '구름조금',
          minTemp: 11.72,
          maxTemp: 18.81,
          rainPrecipitation: 0,
          humidity: 66,
          windSpeed: 4.57,
          clouds: 45,
          dayFeelsLike: 14.15,
        },
        {
          region: '울산',
          weatherIcon: '03d',
          weatherDesc: '구름조금',
          minTemp: 14.42,
          maxTemp: 18.64,
          rainPrecipitation: 0,
          humidity: 65,
          windSpeed: 5.47,
          clouds: 38,
          dayFeelsLike: 15.15,
        },
        {
          region: '광주',
          weatherIcon: '04d',
          weatherDesc: '튼구름',
          minTemp: 13.72,
          maxTemp: 17.13,
          rainPrecipitation: 0,
          humidity: 67,
          windSpeed: 3.3,
          clouds: 55,
          dayFeelsLike: 14.73,
        },
        {
          region: '목포',
          weatherIcon: '04d',
          weatherDesc: '튼구름',
          minTemp: 14.62,
          maxTemp: 16.27,
          rainPrecipitation: 0,
          humidity: 67,
          windSpeed: 3.83,
          clouds: 56,
          dayFeelsLike: 14.64,
        },
        {
          region: '부산',
          weatherIcon: '03d',
          weatherDesc: '구름조금',
          minTemp: 15.15,
          maxTemp: 18.55,
          rainPrecipitation: 0,
          humidity: 64,
          windSpeed: 5.17,
          clouds: 36,
          dayFeelsLike: 15.52,
        },
        {
          region: '제주',
          weatherIcon: '03d',
          weatherDesc: '구름조금',
          minTemp: 7.99,
          maxTemp: 9.36,
          rainPrecipitation: 0,
          humidity: 65,
          windSpeed: 3.78,
          clouds: 32,
          dayFeelsLike: 7.57,
        },
        {
          region: '여수',
          weatherIcon: '03d',
          weatherDesc: '구름조금',
          minTemp: 14.84,
          maxTemp: 17.54,
          rainPrecipitation: 0,
          humidity: 65,
          windSpeed: 3.49,
          clouds: 43,
          dayFeelsLike: 15.26,
        },
      ],
    },
    {
      weatherDate: '2024-05-18',
      dailyNationalWeather: [
        {
          region: '백령',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 13.75,
          maxTemp: 14.61,
          rainPrecipitation: 0,
          humidity: 80,
          windSpeed: 8.93,
          clouds: 5,
          dayFeelsLike: 13.4,
        },
        {
          region: '서울',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 9.93,
          maxTemp: 18.22,
          rainPrecipitation: 0,
          humidity: 71,
          windSpeed: 4.41,
          clouds: 5,
          dayFeelsLike: 13.73,
        },
        {
          region: '춘천',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 10.92,
          maxTemp: 20.28,
          rainPrecipitation: 0,
          humidity: 67,
          windSpeed: 4.42,
          clouds: 5,
          dayFeelsLike: 15.16,
        },
        {
          region: '강릉',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 12.93,
          maxTemp: 20.03,
          rainPrecipitation: 0,
          humidity: 67,
          windSpeed: 5.09,
          clouds: 4,
          dayFeelsLike: 15.74,
        },
        {
          region: '수원',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 10.49,
          maxTemp: 19.15,
          rainPrecipitation: 0,
          humidity: 72,
          windSpeed: 4.44,
          clouds: 5,
          dayFeelsLike: 14.75,
        },
        {
          region: '청주',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 9.65,
          maxTemp: 20.44,
          rainPrecipitation: 0,
          humidity: 69,
          windSpeed: 4.26,
          clouds: 6,
          dayFeelsLike: 15.96,
        },
        {
          region: '울릉/독도',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 16.97,
          maxTemp: 18.19,
          rainPrecipitation: 0,
          humidity: 71,
          windSpeed: 7.62,
          clouds: 5,
          dayFeelsLike: 16.58,
        },
        {
          region: '대전',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 9.65,
          maxTemp: 20.24,
          rainPrecipitation: 0,
          humidity: 68,
          windSpeed: 4.21,
          clouds: 6,
          dayFeelsLike: 16.05,
        },
        {
          region: '안동',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 11.53,
          maxTemp: 20.24,
          rainPrecipitation: 0,
          humidity: 64,
          windSpeed: 4.67,
          clouds: 8,
          dayFeelsLike: 16.13,
        },
        {
          region: '전주',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 10.58,
          maxTemp: 19.55,
          rainPrecipitation: 0,
          humidity: 68,
          windSpeed: 4.19,
          clouds: 8,
          dayFeelsLike: 16.07,
        },
        {
          region: '대구',
          weatherIcon: '02d',
          weatherDesc: '약간의 구름이 낀 하늘',
          minTemp: 11.72,
          maxTemp: 19.53,
          rainPrecipitation: 0,
          humidity: 62,
          windSpeed: 4.03,
          clouds: 17,
          dayFeelsLike: 16.07,
        },
        {
          region: '울산',
          weatherIcon: '03d',
          weatherDesc: '구름조금',
          minTemp: 15.45,
          maxTemp: 19.4,
          rainPrecipitation: 0,
          humidity: 64,
          windSpeed: 3.67,
          clouds: 35,
          dayFeelsLike: 16.9,
        },
        {
          region: '광주',
          weatherIcon: '01d',
          weatherDesc: '맑음',
          minTemp: 14.19,
          maxTemp: 18.11,
          rainPrecipitation: 0,
          humidity: 70,
          windSpeed: 4.54,
          clouds: 10,
          dayFeelsLike: 16.07,
        },
        {
          region: '목포',
          weatherIcon: '02d',
          weatherDesc: '약간의 구름이 낀 하늘',
          minTemp: 15.22,
          maxTemp: 17.3,
          rainPrecipitation: 0,
          humidity: 73,
          windSpeed: 5.32,
          clouds: 11,
          dayFeelsLike: 15.89,
        },
        {
          region: '부산',
          weatherIcon: '03d',
          weatherDesc: '구름조금',
          minTemp: 16.33,
          maxTemp: 19.4,
          rainPrecipitation: 0,
          humidity: 65,
          windSpeed: 3.03,
          clouds: 45,
          dayFeelsLike: 17.23,
        },
        {
          region: '제주',
          weatherIcon: '03d',
          weatherDesc: '구름조금',
          minTemp: 9.36,
          maxTemp: 10.65,
          rainPrecipitation: 0,
          humidity: 79,
          windSpeed: 5.07,
          clouds: 35,
          dayFeelsLike: 7.45,
        },
        {
          region: '여수',
          weatherIcon: '03d',
          weatherDesc: '구름조금',
          minTemp: 15.79,
          maxTemp: 18.66,
          rainPrecipitation: 0,
          humidity: 68,
          windSpeed: 3.6,
          clouds: 28,
          dayFeelsLike: 16.94,
        },
      ],
    },
  ],
  weatherAlert: {
    weatherAlerts: [
      {
        weatherAlertType: '폭염',
        title: '폭염경보',
        announcementTime: '2023-08-14 16:00:00',
        effectiveTime: '2023-08-14 16:00:00',
        content:
          '경기도(양주, 안성, 양평), 강원도(홍천평지), 전라남도(담양, 곡성, 구례, 화순, 순천, 영암), 광주',
      },
      {
        weatherAlertType: '폭염',
        title: '폭염주의보',
        announcementTime: '2023-08-14 16:00:00',
        effectiveTime: '2023-08-14 16:00:00',
        content:
          '경기도(양주, 안성, 양평 제외), 강원도(영월, 정선평지, 횡성, 원주, 철원, 화천, 춘천, 인제평지, 강원북부산지), 충청남도(서천 제외), 충청북도, 전라남도(나주, 장성, 고흥, 보성, 여수, 광양, 장흥, 강진, 해남, 완도, 무안, 함평, 영광, 목포, 신안(흑산면제외), 진도, 흑산도.홍도, 거문도.초도), 전라북도, 경상북도(구미, 영천, 경산, 군위, 청도, 고령, 성주, 칠곡, 김천, 상주, 예천, 안동, 영주, 의성), 경상남도(거창 제외), 제주도(제주도서부, 제주도북부, 제주도동부), 서울, 인천(옹진군 제외), 대전, 대구, 부산, 세종',
      },
    ],
    weatherPreAlerts: [
      {
        announcementTime: '2023-08-14 16:00:00',
        title: '강풍 예비특보',
        weatherAlertType: '강풍',
        contents: [
          {
            content: '08월 15일 새벽(00시~06시) : 울릉도.독도',
          },
        ],
      },
      {
        announcementTime: '2023-08-14 16:00:00',
        title: '풍랑 예비특보',
        weatherAlertType: '풍랑',
        contents: [
          {
            content: '08월 14일 밤(21시~24시) : 동해중부바깥먼바다',
          },
          {
            content:
              '08월 15일 새벽(00시~06시) : 동해남부남쪽안쪽먼바다, 동해남부남쪽바깥먼바다, 동해남부북쪽안쪽먼바다, 동해남부북쪽바깥먼바다, 동해중부안쪽먼바다',
          },
          {
            content:
              '08월 15일 오전(06시~12시) : 동해남부앞바다, 동해중부앞바다, 남해동부안쪽먼바다',
          },
          {
            content: '08월 15일 오후(12시~18시) : 남해동부앞바다(부산앞바다)',
          },
        ],
      },
    ],
  },
  accidentCountDto: {
    accidentCountPerMonth: [
      {
        month: 1,
        deathCnt: 0,
        disappearanceCnt: 0,
        injuryCnt: 0,
      },
      {
        month: 2,
        deathCnt: 0,
        disappearanceCnt: 0,
        injuryCnt: 0,
      },
      {
        month: 3,
        deathCnt: 0,
        disappearanceCnt: 0,
        injuryCnt: 0,
      },
      {
        month: 4,
        deathCnt: 0,
        disappearanceCnt: 0,
        injuryCnt: 0,
      },
      {
        month: 5,
        deathCnt: 0,
        disappearanceCnt: 0,
        injuryCnt: 0,
      },
      {
        month: 6,
        deathCnt: 0,
        disappearanceCnt: 0,
        injuryCnt: 0,
      },
      {
        month: 7,
        deathCnt: 0,
        disappearanceCnt: 0,
        injuryCnt: 0,
      },
      {
        month: 8,
        deathCnt: 0,
        disappearanceCnt: 0,
        injuryCnt: 0,
      },
      {
        month: 9,
        deathCnt: 0,
        disappearanceCnt: 0,
        injuryCnt: 0,
      },
      {
        month: 10,
        deathCnt: 0,
        disappearanceCnt: 0,
        injuryCnt: 0,
      },
      {
        month: 11,
        deathCnt: 0,
        disappearanceCnt: 0,
        injuryCnt: 0,
      },
      {
        month: 12,
        deathCnt: 0,
        disappearanceCnt: 0,
        injuryCnt: 0,
      },
    ],
    province: '전국',
    totalDeathCnt: 0,
    totalDisappearanceCnt: 0,
    totalInjuryCnt: 0,
  },
  nationalPopularWaterPlaces: [
    {
      waterPlaceId: 1,
      waterPlaceName: '관악산계곡어린이물놀이장-신림계곡지구',
      location: '서울특별시 관악구',
      rating: 3.5,
      reviewCnt: 2,
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 2,
      waterPlaceName: '대천천계곡-대천천',
      location: '부산광역시 북구',
      rating: 0,
      reviewCnt: 0,
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 3,
      waterPlaceName: '장산계곡',
      location: '부산광역시 해운대구',
      rating: 0,
      reviewCnt: 0,
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 4,
      waterPlaceName: '장안사 계곡-장안사',
      location: '부산광역시 기장군',
      rating: 0,
      reviewCnt: 0,
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 5,
      waterPlaceName: '용소천 계곡-용소천',
      location: '부산광역시 기장군',
      rating: 0,
      reviewCnt: 0,
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 6,
      waterPlaceName: '임곡교 밑 징검다리-임곡교 밑 상,하류 징검다리 사이',
      location: '광주광역시 광산구',
      rating: 0,
      reviewCnt: 0,
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 7,
      waterPlaceName: '초지공원 앞-산5-8',
      location: '대전광역시 동구',
      rating: 0,
      reviewCnt: 0,
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 8,
      waterPlaceName: '청소년수련원 앞',
      location: '대전광역시 중구',
      rating: 0,
      reviewCnt: 0,
      waterPlaceImageUrl: null,
    },
  ],
  recentReviews: [
    {
      reviewId: 2,
      reviewRating: 4,
      reviewContent: '좋아요',
      reviewCreatedAt: '2024-05-06 22:34:15',
      waterPlaceId: 1,
    },
    {
      reviewId: 1,
      reviewRating: 3,
      reviewContent: 'dd',
      reviewCreatedAt: '2024-03-04 01:34:42',
      waterPlaceId: 1,
    },
  ],
  recentLostFoundBoards: [
    {
      lostFoundBoardId: 18,
      lostFoundBoardCategory: 'FOUND',
      lostFoundBoardTitle: '금오동천에서 키링 봤습니다',
      lostFoundBoardContent: '채팅 주세요',
      lostFoundBoardCreatedAt: '2024-05-06 19:28:16',
    },
    {
      lostFoundBoardId: 17,
      lostFoundBoardCategory: 'FOUND',
      lostFoundBoardTitle: '금오계곡에서 찾았어요',
      lostFoundBoardContent: '아이폰 15 입니다',
      lostFoundBoardCreatedAt: '2024-05-05 21:19:49',
    },
    {
      lostFoundBoardId: 16,
      lostFoundBoardCategory: 'FOUND',
      lostFoundBoardTitle: '핸드폰 잃어버리신 분 채팅주세요',
      lostFoundBoardContent: '관악산 계곡에서 주웠어요~',
      lostFoundBoardCreatedAt: '2024-05-05 21:16:13',
    },
  ],
}
