import { ValleyList } from 'types/valley-list'

export const whole1: ValleyList = {
  content: [
    {
      waterPlaceId: 20,
      waterPlaceName: '봉선사세월교',
      waterPlaceAddr: '경기도 남양주 진접읍 부평리 266-2',
      waterPlaceRating: 4,
      waterPlaceReviewCnt: 7,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1,
      waterPlaceName: '관악산계곡어린이물놀이장-신림계곡지구',
      waterPlaceAddr: '서울특별시 관악구 신림동 210',
      waterPlaceRating: 3.5,
      waterPlaceReviewCnt: 2,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 145,
      waterPlaceName: '무릉계곡-무릉반석',
      waterPlaceAddr: '강원도 동해시 삼화동 산 267',
      waterPlaceRating: 3.25,
      waterPlaceReviewCnt: 4,
      managementType: '일반지역',
      waterPlaceCategory: '산간계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 26,
      waterPlaceName: '삼천리연수원-삼천리연수원 앞',
      waterPlaceAddr: '경기도 남양주 수동면 운수리1-5',
      waterPlaceRating: 3.2,
      waterPlaceReviewCnt: 5,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 478,
      waterPlaceName: '어암계곡-하천(괴산군과 연접지역)',
      waterPlaceAddr: '충정북도 청주시 상당구 미원면 어암리 37',
      waterPlaceRating: 3.2,
      waterPlaceReviewCnt: 5,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 147,
      waterPlaceName: '내평계곡',
      waterPlaceAddr: '강원도 삼척시 근덕면 동막리 693',
      waterPlaceRating: 3,
      waterPlaceReviewCnt: 3,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 112,
      waterPlaceName: '칠봉교',
      waterPlaceAddr: '강원도 원주시 호저면 산현리 519-4',
      waterPlaceRating: 2.83333333333333,
      waterPlaceReviewCnt: 6,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 18,
      waterPlaceName: '용수천-봉암리 서당교 정자 옆',
      waterPlaceAddr: '세종특별자치시 세종시 금남면 봉암리 68-2',
      waterPlaceRating: 2.83333333333333,
      waterPlaceReviewCnt: 6,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 550,
      waterPlaceName: '용수천-공암교 일원',
      waterPlaceAddr: '충청남도 공주시 반포면 공암리 546-78',
      waterPlaceRating: 2.8,
      waterPlaceReviewCnt: 5,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 723,
      waterPlaceName: '하옥계곡-향로교일원',
      waterPlaceAddr: '경상북도 포항시 북구 죽장면 하옥리 산301',
      waterPlaceRating: 2.71428571428571,
      waterPlaceReviewCnt: 7,
      managementType: '중점관리지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 479,
      waterPlaceName: '노산배터-대청댐(보조댐) 아래',
      waterPlaceAddr: '충정북도 청주시 서원구 현도면 노산리 568-1',
      waterPlaceRating: 2.71428571428571,
      waterPlaceReviewCnt: 7,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 476,
      waterPlaceName: '금관숲-숲유원지 앞 하천',
      waterPlaceAddr: '충정북도 청주시 상당구 미원면 금관리 336-4',
      waterPlaceRating: 2.71428571428571,
      waterPlaceReviewCnt: 7,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
  ],
  pageable: {
    sort: {
      empty: false,
      sorted: true,
      unsorted: false,
    },
    offset: 0,
    pageSize: 12,
    pageNumber: 0,
    unpaged: false,
    paged: true,
  },
  last: false,
  totalPages: 184,
  totalElements: 2199,
  first: true,
  sort: {
    empty: false,
    sorted: true,
    unsorted: false,
  },
  number: 0,
  size: 12,
  numberOfElements: 12,
  empty: false,
}

export const whole2: ValleyList = {
  content: [
    {
      waterPlaceId: 1122,
      waterPlaceName: '세종보-금강(세종보 기준 상류 1km, 하류 1km / 총 2km)',
      waterPlaceAddr: '세종특별자치시 세종시 연기면 세종리 752-1',
      waterPlaceRating: 2.71428571428571,
      waterPlaceReviewCnt: 7,
      managementType: '위험지역',
      waterPlaceCategory: '하천(강)',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 731,
      waterPlaceName: '보경사계곡',
      waterPlaceAddr: '경상북도 포항시 북구 송라면 중산리638',
      waterPlaceRating: 2.71428571428571,
      waterPlaceReviewCnt: 7,
      managementType: '중점관리지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1210,
      waterPlaceName: '삼탄유원지-축구장 앞 급류지역',
      waterPlaceAddr: '충청북도 충주시 산척면 명서리 477-1',
      waterPlaceRating: 2.71428571428571,
      waterPlaceReviewCnt: 7,
      managementType: '위험지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 723,
      waterPlaceName: '하옥계곡-향로교일원',
      waterPlaceAddr: '경상북도 포항시 북구 죽장면 하옥리 산301',
      waterPlaceRating: 2.71428571428571,
      waterPlaceReviewCnt: 7,
      managementType: '중점관리지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 114,
      waterPlaceName: '상용곡교',
      waterPlaceAddr: '강원도 원주시 호저면 용곡리 438-2',
      waterPlaceRating: 2.66666666666667,
      waterPlaceReviewCnt: 6,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 28,
      waterPlaceName: '운수교-운수교 앞',
      waterPlaceAddr: '경기도 남양주 수동면 운수리 381-53',
      waterPlaceRating: 2.66666666666667,
      waterPlaceReviewCnt: 3,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 21,
      waterPlaceName: '밤섬 유원지 인근',
      waterPlaceAddr: '경기도 남양주 진접읍 내각리 473-13',
      waterPlaceRating: 2.57142857142857,
      waterPlaceReviewCnt: 7,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1119,
      waterPlaceName: '용수천-성덕리 동연산업 앞',
      waterPlaceAddr: '세종특별자치시 세종시 금남면 성덕리 97-5',
      waterPlaceRating: 2.5,
      waterPlaceReviewCnt: 4,
      managementType: '위험지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1117,
      waterPlaceName: '고복저수지-연서면 고복리',
      waterPlaceAddr: '세종특별자치시 세종시 연서면 고복리 565',
      waterPlaceRating: 2.5,
      waterPlaceReviewCnt: 6,
      managementType: '위험지역',
      waterPlaceCategory: '저수지',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 22,
      waterPlaceName: '황새바위-황새바위 앞',
      waterPlaceAddr: '경기도 남양주 화도읍 구암리 217-4',
      waterPlaceRating: 2.5,
      waterPlaceReviewCnt: 6,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 125,
      waterPlaceName: '아들바위',
      waterPlaceAddr: '강원도 강릉시 주문진읍 주문진리 791-52',
      waterPlaceRating: 2.2,
      waterPlaceReviewCnt: 5,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 781,
      waterPlaceName: '평은면 미림교 밑-미림교 밑',
      waterPlaceAddr: '경상북도 영주시 평은면 용혈리 1311-1',
      waterPlaceRating: 2.2,
      waterPlaceReviewCnt: 5,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
  ],
  pageable: {
    sort: {
      empty: false,
      unsorted: false,
      sorted: true,
    },
    offset: 12,
    pageNumber: 1,
    pageSize: 12,
    unpaged: false,
    paged: true,
  },
  last: false,
  totalPages: 184,
  totalElements: 2199,
  sort: {
    empty: false,
    unsorted: false,
    sorted: true,
  },
  first: false,
  size: 12,
  number: 1,
  numberOfElements: 12,
  empty: false,
}

export const whole3: ValleyList = {
  content: [
    {
      waterPlaceId: 475,
      waterPlaceName: '금봉-하천(금바위아래)',
      waterPlaceAddr: '충정북도 청주시 상당구 미원면 월용리 151',
      waterPlaceRating: 2,
      waterPlaceReviewCnt: 3,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 839,
      waterPlaceName: '빙계계곡 1구역',
      waterPlaceAddr: '경상북도 의성군 춘산면 빙계리 1017-5',
      waterPlaceRating: 2,
      waterPlaceReviewCnt: 4,
      managementType: '중점관리지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 11,
      waterPlaceName: '적십자수련원 앞-804번지 일원',
      waterPlaceAddr: '대전광역시 서구 흑석동 804번지',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 12,
      waterPlaceName: '장평보유원지-749번지 일원',
      waterPlaceAddr: '대전광역시 서구 흑석동 749번지',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 13,
      waterPlaceName: '흑석유원지-775번지 일원',
      waterPlaceAddr: '대전광역시 서구 흑석동 775번지',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 2199,
      waterPlaceName: '옥계천',
      waterPlaceAddr: '전북특별자치도 완주군 운주면 산북리 산124',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '위험지역',
      waterPlaceCategory: '',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 5,
      waterPlaceName: '용소천 계곡-용소천',
      waterPlaceAddr: '부산광역시 기장군 장안읍 용소리 581',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 6,
      waterPlaceName: '임곡교 밑 징검다리-임곡교 밑 상,하류 징검다리 사이',
      waterPlaceAddr: '광주광역시 광산구 선동 311-1',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 23,
      waterPlaceName: '모꼬지캠프-모꼬지캠프 앞',
      waterPlaceAddr: '경기도 남양주 수동면 송천리 3-12',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 25,
      waterPlaceName: '나이스캠프-나이스캠프 앞',
      waterPlaceAddr: '경기도 남양주 수동면 송천리 2-21',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 27,
      waterPlaceName: '감리교연수원-감리교연수원 앞',
      waterPlaceAddr: '경기도 남양주 수동면 운수리 93-1',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 29,
      waterPlaceName: '물골안유원지-물골안유원지 앞',
      waterPlaceAddr: '경기도 남양주 수동면 입석리 503',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
  ],
  pageable: {
    sort: {
      empty: false,
      unsorted: false,
      sorted: true,
    },
    offset: 24,
    pageNumber: 2,
    pageSize: 12,
    unpaged: false,
    paged: true,
  },
  last: false,
  totalPages: 184,
  totalElements: 2199,
  sort: {
    empty: false,
    unsorted: false,
    sorted: true,
  },
  first: false,
  size: 12,
  number: 2,
  numberOfElements: 12,
  empty: false,
}

export const whole4: ValleyList = {
  content: [
    {
      waterPlaceId: 12,
      waterPlaceName: '장평보유원지-749번지 일원',
      waterPlaceAddr: '대전광역시 서구 흑석동 749번지',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 38,
      waterPlaceName: '영평천-백운계곡',
      waterPlaceAddr: '경기도 포천시 이동면 도평리 36 일대',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 2199,
      waterPlaceName: '옥계천',
      waterPlaceAddr: '전북특별자치도 완주군 운주면 산북리 산124',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '위험지역',
      waterPlaceCategory: '',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 11,
      waterPlaceName: '적십자수련원 앞-804번지 일원',
      waterPlaceAddr: '대전광역시 서구 흑석동 804번지',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 41,
      waterPlaceName: '영평천-HJ글램핑장 앞',
      waterPlaceAddr: '경기도 포천시 이동면 도평리 105-3',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 42,
      waterPlaceName: '상촌계곡-',
      waterPlaceAddr: '경기도 양평군 강상면 백석길226-2',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 43,
      waterPlaceName: '흑천-',
      waterPlaceAddr: '경기도 양평군 개군면 공서울길121',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 44,
      waterPlaceName: '선바위-',
      waterPlaceAddr: '경기도 양평군 단월면 삼가리 74-9',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 9,
      waterPlaceName: '침산교 아래',
      waterPlaceAddr: '대전광역시 중구 침산동 398번지',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 8,
      waterPlaceName: '청소년수련원 앞',
      waterPlaceAddr: '대전광역시 중구 침산동 401번지',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 47,
      waterPlaceName: '봉상마을-',
      waterPlaceAddr: '경기도 양평군 단월면 봉상리 666-6',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 48,
      waterPlaceName: '스마일펜션-',
      waterPlaceAddr: '경기도 양평군 단월면 석산로1539-2',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
  ],
  pageable: {
    sort: {
      empty: false,
      unsorted: false,
      sorted: true,
    },
    offset: 36,
    pageNumber: 3,
    pageSize: 12,
    unpaged: false,
    paged: true,
  },
  last: false,
  totalPages: 184,
  totalElements: 2199,
  sort: {
    empty: false,
    unsorted: false,
    sorted: true,
  },
  first: false,
  size: 12,
  number: 3,
  numberOfElements: 12,
  empty: false,
}

export const whole5: ValleyList = {
  content: [
    {
      waterPlaceId: 49,
      waterPlaceName: '소리산소금강야영장(산음천)-',
      waterPlaceAddr: '경기도 양평군 단월면 석산리 689-1',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 50,
      waterPlaceName: '벽계천-',
      waterPlaceAddr: '경기도 양평군 서종면 내수입길15번길3',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 51,
      waterPlaceName: '벽계천-',
      waterPlaceAddr: '경기도 양평군 서종면 화서1로268-21',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 52,
      waterPlaceName: '수능계곡-',
      waterPlaceAddr: '경기도 양평군 서종면 황순원로112',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 53,
      waterPlaceName: '봉상리 부안천-',
      waterPlaceAddr: '경기도 양평군 단월면 봉상리 28-6',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 54,
      waterPlaceName: '사나사 계곡-',
      waterPlaceAddr: '경기도 양평군 옥천면 사나사길 224',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 55,
      waterPlaceName: '흑천-광탄유원지',
      waterPlaceAddr: '경기도 양평군 용문면 광탄리 235-8',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 56,
      waterPlaceName: '흑천-말 부리보',
      waterPlaceAddr: '경기도 양평군 용문면 삼성리 827-3',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 57,
      waterPlaceName: '용문천-천주교수련원',
      waterPlaceAddr: '경기도 양평군 용문면 덕촌리 286',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 58,
      waterPlaceName: '흑천-화전교 상류',
      waterPlaceAddr: '경기도 양평군 용문면 마룡리 152-5',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 59,
      waterPlaceName: '흑천-갈지보',
      waterPlaceAddr: '경기도 양평군 용문면 금곡리 222-1',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 60,
      waterPlaceName: '용문천-준펜션',
      waterPlaceAddr: '경기도 양평군 용문면 마룡리 467-3',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
  ],
  pageable: {
    sort: {
      empty: false,
      unsorted: false,
      sorted: true,
    },
    offset: 48,
    pageNumber: 4,
    pageSize: 12,
    unpaged: false,
    paged: true,
  },
  last: false,
  totalPages: 184,
  totalElements: 2199,
  sort: {
    empty: false,
    unsorted: false,
    sorted: true,
  },
  first: false,
  size: 12,
  number: 4,
  numberOfElements: 12,
  empty: false,
}

export const wholeReview1: ValleyList = {
  content: [
    {
      waterPlaceId: 476,
      waterPlaceName: '금관숲-숲유원지 앞 하천',
      waterPlaceAddr: '충정북도 청주시 상당구 미원면 금관리 336-4',
      waterPlaceRating: 2.71428571428571,
      waterPlaceReviewCnt: 7,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 723,
      waterPlaceName: '하옥계곡-향로교일원',
      waterPlaceAddr: '경상북도 포항시 북구 죽장면 하옥리 산301',
      waterPlaceRating: 2.71428571428571,
      waterPlaceReviewCnt: 7,
      managementType: '중점관리지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 479,
      waterPlaceName: '노산배터-대청댐(보조댐) 아래',
      waterPlaceAddr: '충정북도 청주시 서원구 현도면 노산리 568-1',
      waterPlaceRating: 2.71428571428571,
      waterPlaceReviewCnt: 7,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 731,
      waterPlaceName: '보경사계곡',
      waterPlaceAddr: '경상북도 포항시 북구 송라면 중산리638',
      waterPlaceRating: 2.71428571428571,
      waterPlaceReviewCnt: 7,
      managementType: '중점관리지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 21,
      waterPlaceName: '밤섬 유원지 인근',
      waterPlaceAddr: '경기도 남양주 진접읍 내각리 473-13',
      waterPlaceRating: 2.57142857142857,
      waterPlaceReviewCnt: 7,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 763,
      waterPlaceName: '용담계곡1',
      waterPlaceAddr: '경상북도 안동시 길안면 금곡리 산162',
      waterPlaceRating: 2.71428571428571,
      waterPlaceReviewCnt: 7,
      managementType: '중점관리지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 20,
      waterPlaceName: '봉선사세월교',
      waterPlaceAddr: '경기도 남양주 진접읍 부평리 266-2',
      waterPlaceRating: 4,
      waterPlaceReviewCnt: 7,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1122,
      waterPlaceName: '세종보-금강(세종보 기준 상류 1km, 하류 1km / 총 2km)',
      waterPlaceAddr: '세종특별자치시 세종시 연기면 세종리 752-1',
      waterPlaceRating: 2.71428571428571,
      waterPlaceReviewCnt: 7,
      managementType: '위험지역',
      waterPlaceCategory: '하천(강)',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1210,
      waterPlaceName: '삼탄유원지-축구장 앞 급류지역',
      waterPlaceAddr: '충청북도 충주시 산척면 명서리 477-1',
      waterPlaceRating: 2.71428571428571,
      waterPlaceReviewCnt: 7,
      managementType: '위험지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1117,
      waterPlaceName: '고복저수지-연서면 고복리',
      waterPlaceAddr: '세종특별자치시 세종시 연서면 고복리 565',
      waterPlaceRating: 2.5,
      waterPlaceReviewCnt: 6,
      managementType: '위험지역',
      waterPlaceCategory: '저수지',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 112,
      waterPlaceName: '칠봉교',
      waterPlaceAddr: '강원도 원주시 호저면 산현리 519-4',
      waterPlaceRating: 2.83333333333333,
      waterPlaceReviewCnt: 6,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 114,
      waterPlaceName: '상용곡교',
      waterPlaceAddr: '강원도 원주시 호저면 용곡리 438-2',
      waterPlaceRating: 2.66666666666667,
      waterPlaceReviewCnt: 6,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
  ],
  pageable: {
    sort: {
      empty: false,
      unsorted: false,
      sorted: true,
    },
    offset: 0,
    pageNumber: 0,
    pageSize: 12,
    unpaged: false,
    paged: true,
  },
  last: false,
  totalPages: 184,
  totalElements: 2199,
  sort: {
    empty: false,
    unsorted: false,
    sorted: true,
  },
  first: true,
  size: 12,
  number: 0,
  numberOfElements: 12,
  empty: false,
}

export const wholeReview2: ValleyList = {
  content: [
    {
      waterPlaceId: 18,
      waterPlaceName: '용수천-봉암리 서당교 정자 옆',
      waterPlaceAddr: '세종특별자치시 세종시 금남면 봉암리 68-2',
      waterPlaceRating: 2.83333333333333,
      waterPlaceReviewCnt: 6,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 22,
      waterPlaceName: '황새바위-황새바위 앞',
      waterPlaceAddr: '경기도 남양주 화도읍 구암리 217-4',
      waterPlaceRating: 2.5,
      waterPlaceReviewCnt: 6,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 125,
      waterPlaceName: '아들바위',
      waterPlaceAddr: '강원도 강릉시 주문진읍 주문진리 791-52',
      waterPlaceRating: 2.2,
      waterPlaceReviewCnt: 5,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 478,
      waterPlaceName: '어암계곡-하천(괴산군과 연접지역)',
      waterPlaceAddr: '충정북도 청주시 상당구 미원면 어암리 37',
      waterPlaceRating: 3.2,
      waterPlaceReviewCnt: 5,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 781,
      waterPlaceName: '평은면 미림교 밑-미림교 밑',
      waterPlaceAddr: '경상북도 영주시 평은면 용혈리 1311-1',
      waterPlaceRating: 2.2,
      waterPlaceReviewCnt: 5,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 550,
      waterPlaceName: '용수천-공암교 일원',
      waterPlaceAddr: '충청남도 공주시 반포면 공암리 546-78',
      waterPlaceRating: 2.8,
      waterPlaceReviewCnt: 5,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 26,
      waterPlaceName: '삼천리연수원-삼천리연수원 앞',
      waterPlaceAddr: '경기도 남양주 수동면 운수리1-5',
      waterPlaceRating: 3.2,
      waterPlaceReviewCnt: 5,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1119,
      waterPlaceName: '용수천-성덕리 동연산업 앞',
      waterPlaceAddr: '세종특별자치시 세종시 금남면 성덕리 97-5',
      waterPlaceRating: 2.5,
      waterPlaceReviewCnt: 4,
      managementType: '위험지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 839,
      waterPlaceName: '빙계계곡 1구역',
      waterPlaceAddr: '경상북도 의성군 춘산면 빙계리 1017-5',
      waterPlaceRating: 2,
      waterPlaceReviewCnt: 4,
      managementType: '중점관리지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 145,
      waterPlaceName: '무릉계곡-무릉반석',
      waterPlaceAddr: '강원도 동해시 삼화동 산 267',
      waterPlaceRating: 3.25,
      waterPlaceReviewCnt: 4,
      managementType: '일반지역',
      waterPlaceCategory: '산간계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 147,
      waterPlaceName: '내평계곡',
      waterPlaceAddr: '강원도 삼척시 근덕면 동막리 693',
      waterPlaceRating: 3,
      waterPlaceReviewCnt: 3,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 475,
      waterPlaceName: '금봉-하천(금바위아래)',
      waterPlaceAddr: '충정북도 청주시 상당구 미원면 월용리 151',
      waterPlaceRating: 2,
      waterPlaceReviewCnt: 3,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
  ],
  pageable: {
    sort: {
      empty: false,
      unsorted: false,
      sorted: true,
    },
    offset: 12,
    pageNumber: 1,
    pageSize: 12,
    unpaged: false,
    paged: true,
  },
  last: false,
  totalPages: 184,
  totalElements: 2199,
  sort: {
    empty: false,
    unsorted: false,
    sorted: true,
  },
  first: false,
  size: 12,
  number: 1,
  numberOfElements: 12,
  empty: false,
}

export const wholeReview3: ValleyList = {
  content: [
    {
      waterPlaceId: 28,
      waterPlaceName: '운수교-운수교 앞',
      waterPlaceAddr: '경기도 남양주 수동면 운수리 381-53',
      waterPlaceRating: 2.66666666666667,
      waterPlaceReviewCnt: 3,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1,
      waterPlaceName: '관악산계곡어린이물놀이장-신림계곡지구',
      waterPlaceAddr: '서울특별시 관악구 신림동 210',
      waterPlaceRating: 3.5,
      waterPlaceReviewCnt: 2,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 11,
      waterPlaceName: '적십자수련원 앞-804번지 일원',
      waterPlaceAddr: '대전광역시 서구 흑석동 804번지',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 12,
      waterPlaceName: '장평보유원지-749번지 일원',
      waterPlaceAddr: '대전광역시 서구 흑석동 749번지',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 13,
      waterPlaceName: '흑석유원지-775번지 일원',
      waterPlaceAddr: '대전광역시 서구 흑석동 775번지',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 2199,
      waterPlaceName: '옥계천',
      waterPlaceAddr: '전북특별자치도 완주군 운주면 산북리 산124',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '위험지역',
      waterPlaceCategory: '',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 23,
      waterPlaceName: '모꼬지캠프-모꼬지캠프 앞',
      waterPlaceAddr: '경기도 남양주 수동면 송천리 3-12',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 6,
      waterPlaceName: '임곡교 밑 징검다리-임곡교 밑 상,하류 징검다리 사이',
      waterPlaceAddr: '광주광역시 광산구 선동 311-1',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 25,
      waterPlaceName: '나이스캠프-나이스캠프 앞',
      waterPlaceAddr: '경기도 남양주 수동면 송천리 2-21',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 27,
      waterPlaceName: '감리교연수원-감리교연수원 앞',
      waterPlaceAddr: '경기도 남양주 수동면 운수리 93-1',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 29,
      waterPlaceName: '물골안유원지-물골안유원지 앞',
      waterPlaceAddr: '경기도 남양주 수동면 입석리 503',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 5,
      waterPlaceName: '용소천 계곡-용소천',
      waterPlaceAddr: '부산광역시 기장군 장안읍 용소리 581',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
  ],
  pageable: {
    sort: {
      empty: false,
      unsorted: false,
      sorted: true,
    },
    offset: 24,
    pageNumber: 2,
    pageSize: 12,
    unpaged: false,
    paged: true,
  },
  last: false,
  totalPages: 184,
  totalElements: 2199,
  sort: {
    empty: false,
    unsorted: false,
    sorted: true,
  },
  first: false,
  size: 12,
  number: 2,
  numberOfElements: 12,
  empty: false,
}

export const wholeReview4: ValleyList = {
  content: [
    {
      waterPlaceId: 8,
      waterPlaceName: '청소년수련원 앞',
      waterPlaceAddr: '대전광역시 중구 침산동 401번지',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 38,
      waterPlaceName: '영평천-백운계곡',
      waterPlaceAddr: '경기도 포천시 이동면 도평리 36 일대',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 2199,
      waterPlaceName: '옥계천',
      waterPlaceAddr: '전북특별자치도 완주군 운주면 산북리 산124',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '위험지역',
      waterPlaceCategory: '',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 6,
      waterPlaceName: '임곡교 밑 징검다리-임곡교 밑 상,하류 징검다리 사이',
      waterPlaceAddr: '광주광역시 광산구 선동 311-1',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 41,
      waterPlaceName: '영평천-HJ글램핑장 앞',
      waterPlaceAddr: '경기도 포천시 이동면 도평리 105-3',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 42,
      waterPlaceName: '상촌계곡-',
      waterPlaceAddr: '경기도 양평군 강상면 백석길226-2',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 43,
      waterPlaceName: '흑천-',
      waterPlaceAddr: '경기도 양평군 개군면 공서울길121',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 44,
      waterPlaceName: '선바위-',
      waterPlaceAddr: '경기도 양평군 단월면 삼가리 74-9',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 5,
      waterPlaceName: '용소천 계곡-용소천',
      waterPlaceAddr: '부산광역시 기장군 장안읍 용소리 581',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 2,
      waterPlaceName: '대천천계곡-대천천',
      waterPlaceAddr: '부산광역시 북구 화명동 2102번지',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 47,
      waterPlaceName: '봉상마을-',
      waterPlaceAddr: '경기도 양평군 단월면 봉상리 666-6',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 48,
      waterPlaceName: '스마일펜션-',
      waterPlaceAddr: '경기도 양평군 단월면 석산로1539-2',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
  ],
  pageable: {
    sort: {
      empty: false,
      unsorted: false,
      sorted: true,
    },
    offset: 36,
    pageNumber: 3,
    pageSize: 12,
    unpaged: false,
    paged: true,
  },
  last: false,
  totalPages: 184,
  totalElements: 2199,
  sort: {
    empty: false,
    unsorted: false,
    sorted: true,
  },
  first: false,
  size: 12,
  number: 3,
  numberOfElements: 12,
  empty: false,
}

export const wholeReview5: ValleyList = {
  content: [
    {
      waterPlaceId: 49,
      waterPlaceName: '소리산소금강야영장(산음천)-',
      waterPlaceAddr: '경기도 양평군 단월면 석산리 689-1',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 50,
      waterPlaceName: '벽계천-',
      waterPlaceAddr: '경기도 양평군 서종면 내수입길15번길3',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 51,
      waterPlaceName: '벽계천-',
      waterPlaceAddr: '경기도 양평군 서종면 화서1로268-21',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 52,
      waterPlaceName: '수능계곡-',
      waterPlaceAddr: '경기도 양평군 서종면 황순원로112',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 53,
      waterPlaceName: '봉상리 부안천-',
      waterPlaceAddr: '경기도 양평군 단월면 봉상리 28-6',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 54,
      waterPlaceName: '사나사 계곡-',
      waterPlaceAddr: '경기도 양평군 옥천면 사나사길 224',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 55,
      waterPlaceName: '흑천-광탄유원지',
      waterPlaceAddr: '경기도 양평군 용문면 광탄리 235-8',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 56,
      waterPlaceName: '흑천-말 부리보',
      waterPlaceAddr: '경기도 양평군 용문면 삼성리 827-3',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 57,
      waterPlaceName: '용문천-천주교수련원',
      waterPlaceAddr: '경기도 양평군 용문면 덕촌리 286',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 58,
      waterPlaceName: '흑천-화전교 상류',
      waterPlaceAddr: '경기도 양평군 용문면 마룡리 152-5',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 59,
      waterPlaceName: '흑천-갈지보',
      waterPlaceAddr: '경기도 양평군 용문면 금곡리 222-1',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '중점관리지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 60,
      waterPlaceName: '용문천-준펜션',
      waterPlaceAddr: '경기도 양평군 용문면 마룡리 467-3',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
  ],
  pageable: {
    sort: {
      empty: false,
      unsorted: false,
      sorted: true,
    },
    offset: 48,
    pageNumber: 4,
    pageSize: 12,
    unpaged: false,
    paged: true,
  },
  last: false,
  totalPages: 184,
  totalElements: 2199,
  sort: {
    empty: false,
    unsorted: false,
    sorted: true,
  },
  first: false,
  size: 12,
  number: 4,
  numberOfElements: 12,
  empty: false,
}

export const seoul: ValleyList = {
  content: [
    {
      waterPlaceId: 1,
      waterPlaceName: '관악산계곡어린이물놀이장-신림계곡지구',
      waterPlaceAddr: '서울특별시 관악구 신림동 210',
      waterPlaceRating: 3.5,
      waterPlaceReviewCnt: 2,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1366,
      waterPlaceName: '관악산계곡어린이물놀이장',
      waterPlaceAddr: '서울특별시 관악구 신림동 210',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 2192,
      waterPlaceName: '관악산계곡',
      waterPlaceAddr: '서울특별시 관악구 대학21길 3-16',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '위험지역',
      waterPlaceCategory: '',
      waterPlaceImageUrl: null,
    },
  ],
  pageable: {
    sort: {
      empty: false,
      unsorted: false,
      sorted: true,
    },
    offset: 0,
    pageNumber: 0,
    pageSize: 12,
    unpaged: false,
    paged: true,
  },
  last: true,
  totalPages: 1,
  totalElements: 3,
  sort: {
    empty: false,
    unsorted: false,
    sorted: true,
  },
  first: true,
  size: 12,
  number: 0,
  numberOfElements: 3,
  empty: false,
}

export const seoulReview: ValleyList = {
  content: [
    {
      waterPlaceId: 1,
      waterPlaceName: '관악산계곡어린이물놀이장-신림계곡지구',
      waterPlaceAddr: '서울특별시 관악구 신림동 210',
      waterPlaceRating: 3.5,
      waterPlaceReviewCnt: 2,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1366,
      waterPlaceName: '관악산계곡어린이물놀이장',
      waterPlaceAddr: '서울특별시 관악구 신림동 210',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 2192,
      waterPlaceName: '관악산계곡',
      waterPlaceAddr: '서울특별시 관악구 대학21길 3-16',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '위험지역',
      waterPlaceCategory: '',
      waterPlaceImageUrl: null,
    },
  ],
  pageable: {
    sort: {
      empty: false,
      unsorted: false,
      sorted: true,
    },
    offset: 0,
    pageNumber: 0,
    pageSize: 12,
    unpaged: false,
    paged: true,
  },
  last: true,
  totalPages: 1,
  totalElements: 3,
  sort: {
    empty: false,
    unsorted: false,
    sorted: true,
  },
  first: true,
  size: 12,
  number: 0,
  numberOfElements: 3,
  empty: false,
}

export const jejuWhole: ValleyList = {
  content: [
    {
      waterPlaceId: 1092,
      waterPlaceName: '월대천-외도월대천',
      waterPlaceAddr: '제주특별자치도 제주시 외도동 외도2동 2551번지',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1093,
      waterPlaceName: '옹포천-한림옹포천',
      waterPlaceAddr: '제주특별자치도 제주시 한림읍 명월리 887-1',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1094,
      waterPlaceName: '강정천',
      waterPlaceAddr: '제주특별자치도 서귀포시 강정동 2673-6',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1095,
      waterPlaceName: '돈내코계곡',
      waterPlaceAddr: '제주특별자치도 서귀포시 상효동 1463',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1096,
      waterPlaceName: '중문천',
      waterPlaceAddr: '제주특별자치도 서귀포시 중문동 2631',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1097,
      waterPlaceName: '솜반천',
      waterPlaceAddr: '제주특별자치도 서귀포시 서홍동 1223-7',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1098,
      waterPlaceName: '속골',
      waterPlaceAddr: '제주특별자치도 서귀포시 서호동 85',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1099,
      waterPlaceName: '산지물',
      waterPlaceAddr: '제주특별자치도 서귀포시 동홍동 1288',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1100,
      waterPlaceName: '정모시 쉼터',
      waterPlaceAddr: '제주특별자치도 서귀포시 서귀동 109',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1969,
      waterPlaceName: '월대천',
      waterPlaceAddr: '제주특별자치도 제주시 외도동 외도2동 2551번지',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1970,
      waterPlaceName: '옹포천',
      waterPlaceAddr: '제주특별자치도 제주시 한림읍 명월리 887-1',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
  ],
  pageable: {
    sort: {
      empty: false,
      unsorted: false,
      sorted: true,
    },
    offset: 0,
    pageNumber: 0,
    pageSize: 12,
    unpaged: false,
    paged: true,
  },
  last: true,
  totalPages: 1,
  totalElements: 11,
  sort: {
    empty: false,
    unsorted: false,
    sorted: true,
  },
  first: true,
  size: 12,
  number: 0,
  numberOfElements: 11,
  empty: false,
}

export const jejuWholeReview: ValleyList = {
  content: [
    {
      waterPlaceId: 1092,
      waterPlaceName: '월대천-외도월대천',
      waterPlaceAddr: '제주특별자치도 제주시 외도동 외도2동 2551번지',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1093,
      waterPlaceName: '옹포천-한림옹포천',
      waterPlaceAddr: '제주특별자치도 제주시 한림읍 명월리 887-1',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1094,
      waterPlaceName: '강정천',
      waterPlaceAddr: '제주특별자치도 서귀포시 강정동 2673-6',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1095,
      waterPlaceName: '돈내코계곡',
      waterPlaceAddr: '제주특별자치도 서귀포시 상효동 1463',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '계곡',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1096,
      waterPlaceName: '중문천',
      waterPlaceAddr: '제주특별자치도 서귀포시 중문동 2631',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1097,
      waterPlaceName: '솜반천',
      waterPlaceAddr: '제주특별자치도 서귀포시 서홍동 1223-7',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1098,
      waterPlaceName: '속골',
      waterPlaceAddr: '제주특별자치도 서귀포시 서호동 85',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1099,
      waterPlaceName: '산지물',
      waterPlaceAddr: '제주특별자치도 서귀포시 동홍동 1288',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1100,
      waterPlaceName: '정모시 쉼터',
      waterPlaceAddr: '제주특별자치도 서귀포시 서귀동 109',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1969,
      waterPlaceName: '월대천',
      waterPlaceAddr: '제주특별자치도 제주시 외도동 외도2동 2551번지',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1970,
      waterPlaceName: '옹포천',
      waterPlaceAddr: '제주특별자치도 제주시 한림읍 명월리 887-1',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
  ],
  pageable: {
    sort: {
      empty: false,
      unsorted: false,
      sorted: true,
    },
    offset: 0,
    pageNumber: 0,
    pageSize: 12,
    unpaged: false,
    paged: true,
  },
  last: true,
  totalPages: 1,
  totalElements: 11,
  sort: {
    empty: false,
    unsorted: false,
    sorted: true,
  },
  first: true,
  size: 12,
  number: 0,
  numberOfElements: 11,
  empty: false,
}

export const jeju: ValleyList = {
  content: [
    {
      waterPlaceId: 1092,
      waterPlaceName: '월대천-외도월대천',
      waterPlaceAddr: '제주특별자치도 제주시 외도동 외도2동 2551번지',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1093,
      waterPlaceName: '옹포천-한림옹포천',
      waterPlaceAddr: '제주특별자치도 제주시 한림읍 명월리 887-1',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1969,
      waterPlaceName: '월대천',
      waterPlaceAddr: '제주특별자치도 제주시 외도동 외도2동 2551번지',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
    {
      waterPlaceId: 1970,
      waterPlaceName: '옹포천',
      waterPlaceAddr: '제주특별자치도 제주시 한림읍 명월리 887-1',
      waterPlaceRating: 0,
      waterPlaceReviewCnt: 0,
      managementType: '일반지역',
      waterPlaceCategory: '하천',
      waterPlaceImageUrl: null,
    },
  ],
  pageable: {
    sort: {
      empty: false,
      unsorted: false,
      sorted: true,
    },
    offset: 0,
    pageNumber: 0,
    pageSize: 12,
    unpaged: false,
    paged: true,
  },
  last: true,
  totalPages: 1,
  totalElements: 4,
  sort: {
    empty: false,
    unsorted: false,
    sorted: true,
  },
  first: true,
  size: 12,
  number: 0,
  numberOfElements: 4,
  empty: false,
}
